import test from 'node:test';
import assert from 'node:assert/strict';
import {openingProgress,openingCounts,normalInventoryEnabled,createOpeningApi} from './inventoryOpening.js';
const materials=[{id:'a'},{id:'b'}];
const storage=()=>{const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};};
const id='11111111-1111-4111-8111-111111111111';
function harness(rpc,store=storage(),who=async()=>'admin'){return createOpeningApi({rpc},{userId:'admin',projectRef:'project',assertAccess:()=>{},currentUserId:who,storage:store,uuid:()=>id});}
test('blank differs from physically counted zero; decimals supported',()=>{assert.deepEqual(openingProgress(materials,{a:'0',b:''}),{counts:{a:0},entered:1,total:2,complete:false});assert.equal(openingProgress(materials,{a:'2.75',b:'0'}).complete,true);});
test('counts reject negative, nonfinite, exponent and imprecise values',()=>{for(const a of ['-1','Infinity','NaN','1e2','9007199254740992','1,2','0.10000000000000001'])assert.throws(()=>openingCounts(materials,{a}));});
test('normal operations require both deployment permission and verified server activation',()=>{for(const status of [null,{}, {phase:3,active:true},{phase:4,active:false}])assert.equal(normalInventoryEnabled({mutationsEnabled:true},status),false);assert.equal(normalInventoryEnabled({mutationsEnabled:false},{phase:4,active:true}),false);assert.equal(normalInventoryEnabled({mutationsEnabled:true},{phase:4,active:true}),true);});
test('setup has a strict action/argument allowlist',async()=>{let calls=0;const api=harness(async()=>{calls++;return {data:{}};});assert.throws(()=>api.run('receive_purchase',{}));assert.throws(()=>api.run('save_opening_draft',{revision:0,manifest:[],counts:{},extra:1}));assert.equal(calls,0);});
test('actor change blocks before network',async()=>{let calls=0;const api=harness(async()=>{calls++;},storage(),async()=>'other');await assert.rejects(api.status(),/บัญชี/);assert.equal(calls,0);});
test('uncertain response persists exact intent across reload and retries same UUID',async()=>{const store=storage();let calls=[];const input={revision:0,manifest:[],counts:{a:2.75}};const api=harness(async(name,args)=>{calls.push({name,args});throw new Error('network lost');},store);await assert.rejects(api.run('save_opening_draft',input));assert.equal(api.pending().id,id);assert.throws(()=>api.run('save_opening_draft',input),/ค้าง/);const resumed=harness(async(name,args)=>{calls.push({name,args});return {data:{saved:true,revision:1}};},store);await resumed.retry();assert.deepEqual(calls[0],calls[1]);assert.equal(resumed.pending(),null);});
test('structured rollback retires failed intent, no automatic retry',async()=>{let calls=0;const api=harness(async()=>{calls++;return {error:{code:'P0001',message:'Draft changed'}};});await assert.rejects(api.run('save_opening_draft',{revision:0,manifest:[],counts:{}}),/Draft changed/);assert.equal(api.pending(),null);assert.equal(calls,1);});
test('double submit shares one in-flight call',async()=>{let calls=0,finish;const api=harness(async()=>{calls++;return new Promise(r=>{finish=r;});});const input={revision:0,manifest:[],counts:{}};const a=api.run('save_opening_draft',input),b=api.run('save_opening_draft',input);await new Promise(r=>setImmediate(r));assert.equal(calls,1);finish({data:{saved:true}});await Promise.all([a,b]);});
test('failed persistence prevents any RPC',async()=>{let calls=0;const api=harness(async()=>{calls++;},{getItem:()=>null,setItem:()=>{throw new Error('storage full');}});await assert.rejects(api.run('save_opening_draft',{revision:0,manifest:[],counts:{}}),/storage full/);assert.equal(calls,0);});
test('lookup resolution requires completed matching operation kind',async()=>{const store=storage();const first=harness(async()=>{throw new Error('lost');},store);await assert.rejects(first.run('save_opening_draft',{revision:0,manifest:[],counts:{}}));const wrong=harness(async()=>({data:{found:true,completed:true,kind:'purchase',result:{}}}),store);await assert.rejects(wrong.resolve(),/ไม่ตรง/);assert.ok(wrong.pending());const correct=harness(async()=>({data:{found:true,completed:true,kind:'opening_draft',result:{saved:true}}}),store);assert.deepEqual(await correct.resolve(),{saved:true});assert.equal(correct.pending(),null);});
