import React,{useEffect,useMemo,useState} from 'react';
import {openingProgress} from '../lib/inventoryOpening.js';
export function InventoryOpeningBalance({api,onChanged,onBusyChange}){
 const [state,setState]=useState(null),[values,setValues]=useState({}),[search,setSearch]=useState(''),[uncounted,setUncounted]=useState(false),[review,setReview]=useState(false),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[pending,setPending]=useState(null);
 async function load(){const next=await api.status();setState(next);setValues(next.counts||{});setPending(api.pending());setReview(false);setUncounted(false);setConfirmation('');}
 useEffect(()=>{let alive=true;api.status().then(next=>{if(alive){setState(next);setValues(next.counts||{});setPending(api.pending());}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[api]);
 useEffect(()=>{onBusyChange?.(busy);return()=>onBusyChange?.(false);},[busy,onBusyChange]);
 const progress=useMemo(()=>{try{return {...openingProgress(state?.manifest||[],values),error:null};}catch(e){return {counts:{},entered:0,total:state?.manifest?.length||0,complete:false,error:e.message};}},[state,values]);
 const dirty=state&&JSON.stringify(progress.counts)!==JSON.stringify(state.counts||{});
 useEffect(()=>{if(!dirty)return;const prevent=e=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[dirty]);
 async function execute(action,input){if(busy)return;setBusy(true);setError('');setMessage('');try{await api.run(action,input);await load();onChanged();setMessage('บันทึกสำเร็จ');}catch(e){setError(e.message);setPending(api.pending());}finally{setBusy(false);}}
 async function recover(retry){setBusy(true);setError('');try{const result=retry?await api.retry():await api.resolve();if(result){await load();onChanged();}else setMessage('ยังไม่พบผลที่บันทึกไว้ สามารถส่งรายการเดิมอีกครั้งโดยใช้รหัสเดิม');}catch(e){setError(e.message);}finally{setPending(api.pending());setBusy(false);}}
 const rows=(state?.manifest||[]).filter(m=>(review||m.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()))&&(review||!uncounted||!(m.id in progress.counts)));
 return <section className="inv-panel inv-opening" aria-label="ยอดตั้งต้นจากการตรวจนับ"><h2>ยอดตั้งต้นจากการตรวจนับ</h2><button disabled={busy} onClick={async()=>{if(dirty&&!window.confirm('โหลดใหม่จะทิ้งเฉพาะการแก้ไขที่ยังไม่บันทึก ต้องการโหลดหรือไม่?'))return;setBusy(true);try{await load();setError('');}catch(e){setError(e.message);}finally{setBusy(false);}}}>โหลดร่างที่บันทึกไว้</button><p>บันทึกร่างได้หลายครั้งโดยยังไม่เปลี่ยนสต๊อก ช่องว่าง = ยังไม่นับ · 0 = ตรวจนับแล้วไม่มีของ</p>
  {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
  {!state?<p>กำลังโหลด…</p>:<>
  {state.active?<p role="status">เปิดใช้งานคลังแล้ว ยอดตั้งต้นถูกเก็บเป็นประวัติ</p>:<p role="status">คลังยังไม่เปิดใช้งาน — งานรับเข้า/เบิกยังถูกระงับ</p>}
  {pending&&<aside role="alert"><p>มีรายการที่ยังต้องตรวจสอบผล ห้ามสร้างรายการใหม่แทน</p><button disabled={busy} onClick={()=>recover(false)}>ตรวจสอบผล</button><button disabled={busy} onClick={()=>recover(true)}>ส่งรายการเดิมอีกครั้ง</button></aside>}
  <p><strong>กรอกแล้ว {progress.entered} / {progress.total}</strong>{dirty?' · ยังไม่ได้บันทึกการแก้ไข':''}{state.updated_at?' · บันทึกล่าสุด '+new Date(state.updated_at).toLocaleString('th-TH'):''}</p>
  {!review&&<div className="inv-actions"><label>ค้นหาวัสดุ <input value={search} onChange={e=>setSearch(e.target.value)} /></label><label><input type="checkbox" checked={uncounted} onChange={e=>setUncounted(e.target.checked)}/>เฉพาะที่ยังไม่นับ</label></div>}
  {progress.error&&<p role="alert">{progress.error}</p>}
  <div className="inv-opening-table"><table><thead><tr><th>วัสดุ</th><th>หน่วย</th><th>จำนวนที่นับได้</th></tr></thead><tbody>{rows.map(m=><tr key={m.id}><td>{m.name}</td><td>{m.unit}</td><td>{review||state.finalized?<span>{values[m.id]??'ยังไม่นับ'}</span>:<input aria-label={'จำนวน '+m.name} inputMode="decimal" value={values[m.id]??''} disabled={busy||Boolean(pending)} placeholder="ยังไม่นับ" onChange={e=>setValues(v=>({...v,[m.id]:e.target.value}))}/>}</td></tr>)}</tbody></table></div>
  {!state.finalized&&!pending&&<div className="inv-actions"><button disabled={busy||!!progress.error||!dirty} onClick={()=>execute('save_opening_draft',{revision:state.revision,manifest:state.manifest,counts:progress.counts})}>บันทึกร่าง</button><button disabled={busy||!progress.complete||dirty} onClick={()=>{setReview(!review);setConfirmation('');}}>{review?'กลับไปแก้ไข':'ตรวจทานยอดทั้งหมด'}</button></div>}
  {review&&!state.finalized&&<div role="group" aria-label="ยืนยันยอดตั้งต้น"><p role="alert">การยืนยันจะลงยอดสต๊อกจริงครั้งเดียว ไม่ใช่รายการซื้อ และจะแก้ร่างไม่ได้อีก กรุณาตรวจนับและตรวจทานให้ครบก่อน</p><label>พิมพ์ ยืนยันยอดตั้งต้น <input value={confirmation} disabled={busy} onChange={e=>setConfirmation(e.target.value)}/></label><button disabled={busy||!!pending||!progress.complete||dirty||confirmation!=='ยืนยันยอดตั้งต้น'} onClick={()=>execute('finalize_opening_balance',{revision:state.revision,manifest:state.manifest,confirmation:'FINALIZE OPENING BALANCE'})}>ยืนยันยอดตั้งต้น</button></div>}
  {state.finalized&&!state.active&&<div role="group" aria-label="เปิดใช้งานคลัง"><p>ยอดตั้งต้นบันทึกแล้ว · {state.verified?'ตรวจสอบบัญชีตรงกัน':'ตรวจสอบไม่ผ่าน ห้ามเปิดใช้งาน'}</p><p>การเปิดใช้งานจะอนุญาตให้พนักงานรับเข้า ขอเบิก และทำรายการสต๊อกได้</p><label>พิมพ์ เปิดใช้งานคลัง <input value={confirmation} disabled={busy||!state.verified} onChange={e=>setConfirmation(e.target.value)}/></label><button disabled={busy||!!pending||!state.verified||confirmation!=='เปิดใช้งานคลัง'} onClick={()=>execute('activate_inventory',{finalized_operation_id:state.finalized_operation_id,confirmation:'ACTIVATE INVENTORY'})}>เปิดใช้งานคลัง</button></div>}
  </>}
 </section>;
}
