import React, {useEffect, useMemo, useState} from 'react';
import {Download, RefreshCw} from 'lucide-react';
import {loadReportData, localDay, modelSummary, allocationRows, sumAmounts, negative, reportCSV, WORKFLOW_LABELS, MOVEMENT_LABELS} from '../lib/inventoryReports.js';
import {reportProjection,REPAIR_CATEGORY,categoryOverview} from '../lib/inventoryReportFilters.js';
import {PRODUCT_CATEGORIES} from '../lib/inventoryReports.js';
import {downloadCSV} from '../utils/csv.js';
const requestColumns=[['order_ref','ออเดอร์ / อ้างอิง'],['model_name','รุ่น ณ วันที่ขอ'],['category','หมวด'],['created_at','เวลาสร้าง'],['status_label','สถานะปัจจุบัน'],['requester','ผู้ขอ'],['cancelled_at','เวลายกเลิก'],['model_id','รหัสรุ่น'],['request_id','รหัสคำขอ']];
requestColumns.push(['accounting_evidence','Historical inventory evidence']);
const movementColumns=[['occurred_at','เวลา'],['material_name','วัตถุดิบ'],['reason_label','ประเภท'],['delta','เปลี่ยนแปลง'],['unit','หน่วย'],['qty_before','ก่อน'],['qty_after','หลัง'],['reference','อ้างอิง'],['supplier_source','ผู้ขาย / แหล่งที่ซื้อ'],['document_type','เอกสาร'],['po_number','PO'],['invoice_number','Invoice'],['note','หมายเหตุ'],['actor_id','รหัสผู้ทำรายการ'],['id','รหัสรายการ'],['category','หมวด'],['model_name','รุ่น'],['operation_id','รหัสการบันทึก'],['version_before','รุ่นยอดก่อน'],['version_after','รุ่นยอดหลัง']];
movementColumns.push(['material_id','รหัสวัตถุดิบ']);
const balanceColumns=[['name','วัตถุดิบ'],['unit','หน่วย'],['opening','ต้นงวด'],['opening_additions','ยอดตั้งต้นเพิ่มเติม'],['purchase','รับเข้า'],['issue','เบิกทั้งหมด'],['returned','คืนทั้งหมด'],['net_usage','ใช้สุทธิ'],['production_issue','เบิกผลิต'],['repair_issue','เบิกซ่อม'],['production_returned','คืนผลิต'],['repair_returned','คืนซ่อม'],['adjustment_in','ปรับเพิ่ม'],['adjustment_out','ปรับลด'],['closing','ปลายงวด'],['coverage','ความครอบคลุม']];
export function ReportTable({rows,columns}) {
  const [page,setPage]=useState(0);const last=Math.max(0,Math.ceil(rows.length/25)-1);const current=Math.min(page,last);
  return <><div className="inv-table-scroll"><table><thead><tr>{columns.map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{rows.slice(current*25,(current+1)*25).map((r,i)=><tr key={`${r.request_id||r.id||'row'}:${i}`}>{columns.map(([key])=><td key={key}>{r[key]==null?'ไม่ครอบคลุม':String(r[key])}</td>)}</tr>)}</tbody></table></div>
    {!rows.length&&<p className="inv-empty">ไม่มีรายการในช่วงที่เลือก</p>}
    {last>0&&<div className="inv-toolbar"><button disabled={!current} onClick={()=>setPage(current-1)}>ก่อนหน้า</button><span>หน้า {current+1}/{last+1} · {rows.length} รายการ</span><button disabled={current===last} onClick={()=>setPage(current+1)}>ถัดไป</button></div>}</>;
}
export function InventoryReports({api,role,revision}) {
  const today=localDay(new Date());const [from,setFrom]=useState(today.slice(0,8)+'01');const [to,setTo]=useState(today);
  const [tab,setTab]=useState('dashboard');const [reload,setReload]=useState(0);const [loadedData,setData]=useState(null);const [error,setError]=useState(null);const [busy,setBusy]=useState(true);
  const [overviewBasis,setOverviewBasis]=useState('issued');const [category,setCategory]=useState('');const [material,setMaterial]=useState('');const [search,setSearch]=useState('');const [status,setStatus]=useState('');
  useEffect(()=>{let active=true;setBusy(true);setError(null);setData(null);loadReportData(api,role,from,to).then(d=>{if(active)setData({...d,from,to});}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[api,role,from,to,revision,reload]);
  const data=loadedData?.from===from&&loadedData?.to===to?loadedData:null;
  const projection=useMemo(()=>data?reportProjection(data,from,to,{category,status,search,material}):{rows:[],moves:[],allocations:[],balances:[],requirements:[],scoped:false},[data,from,to,category,status,search,material]);
  const rows=projection.rows.map(r=>({...r,status_label:WORKFLOW_LABELS[r.status]||r.status}));

  const categories=data&&role==='admin'?categoryOverview(data.requests,from,to,{basis:overviewBasis,category,status,search}):[];
  const summary=modelSummary(rows);const moves=projection.moves.map(m=>({...m,reason_label:MOVEMENT_LABELS[m.reason]||m.reason}));
  const allocations=projection.allocations;
  const balances=projection.balances.map(b=>({...b,net_usage:sumAmounts([b.issue,negative(b.returned)])}));
  const requirements=projection.requirements.map(r=>({...r,status_label:WORKFLOW_LABELS[r.status]||r.status}));
  const tabs=role==='admin'?[['dashboard','ภาพรวม'],['requests','ออเดอร์ / คำขอ'],['stock','ยอดและการใช้'],['movements','ประวัติ / รายละเอียด']]:[['dashboard','ภาพรวม'],['stock','ยอดและการใช้'],['movements','ประวัติ / รายละเอียด']];
  const canExport=data&&!busy&&!error&&!data.mismatches.length;
  function exportRows(name,values,columns){if(!canExport)return;downloadCSV(`${name}_${from}_${to}.csv`,reportCSV(values,columns,{from,to,timezone:'Asia/Bangkok',captured_at:data.capturedAt,movement_cutoff:data.cutoff,material_filter:material||'all',category_filter:category||'all',scope:projection.scoped?'allocated request usage; no category stock balance':'whole ledger',request_search:search,status_filter:status||'all',overview_date_basis:overviewBasis,status_basis:name==='categories'?'current at capture; selection by '+overviewBasis+' Bangkok dates, one count per request':'current at capture; request period by creation; movement period by occurrence'}));}
  const exportButton=(name,values,columns,label)=><button disabled={!canExport} onClick={()=>exportRows(name,values,columns)}><Download size={14}/> {label}</button>;
  return <section className="inv-reports"><div className="inv-toolbar"><h2>รายงาน</h2><button disabled={busy} onClick={()=>setReload(n=>n+1)}><RefreshCw size={16}/> โหลดใหม่</button></div>
    <div className="inv-filters"><label>ตั้งแต่<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>ถึง<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>
    <label>หมวดสินค้า<select aria-label="หมวดรายงาน" value={category} onChange={e=>setCategory(e.target.value)}><option value="">ทั้งหมด</option>{[...PRODUCT_CATEGORIES,REPAIR_CATEGORY].map(c=><option key={c}>{c}</option>)}</select></label>
    {projection.scoped&&<p className="inv-notice">ยอดเบิก/คืนตามหมวด · ไม่ใช่ยอดคงคลังแยกหมวด</p>}
    <details><summary>ขอบเขตรายงาน</summary><p className="inv-muted">เวลาไทย · ภาพรวมเลือกวันเบิกจริง/วันสร้างได้ · แท็บคำขอใช้วันสร้าง แสดงสถานะปัจจุบัน · การรับ/เบิก/คืนตามวันที่เคลื่อนไหว ไม่ใช่วันที่จัดส่งสินค้า</p></details>
    <div className="inv-actions"><button type="button" disabled title="ยังไม่เชื่อมต่อ Google Sheets">เปิด Google Sheet · เร็วๆ นี้</button></div>
    <nav className="inv-subnav">{tabs.map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</nav>
    {busy&&<p role="status">กำลังโหลดข้อมูลรายงานทุกหน้า…</p>}{error&&<p role="alert">{error} — ไม่แสดงหรือส่งออกรายงานบางส่วน</p>}
    {data&&<><p className="inv-muted">ข้อมูลที่โหลดเมื่อ {new Date(data.capturedAt).toLocaleString('th-TH')} · หากมีงานระหว่างโหลด ให้โหลดใหม่ก่อนใช้ปิดยอด</p>
      {data.mismatches.length>0&&<p role="alert">ยอดสรุปและรายละเอียดไม่ตรงกัน อาจมีรายการใหม่ระหว่างโหลด หยุดส่งออกและโหลดใหม่ หากยังไม่ตรงให้ตรวจสอบ: {data.mismatches.join(', ')}</p>}
      {role==='admin'&&<div className="inv-filters"><label>ค้นหาออเดอร์ / รุ่น<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>สถานะ<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">ทั้งหมด</option>{Object.entries(WORKFLOW_LABELS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div>}
      {tab==='dashboard'&&<>{role==='purchasing'&&<p>บัญชีการใช้วัตถุดิบตามหมวดไม่แสดงข้อมูลลูกค้า/คำขอ และไม่สมมติจำนวนออเดอร์จากยอดเบิก</p>}{role==='admin'&&<>
        <h3>จำนวนคำขอแยกตามหมวดสินค้า</h3>
        <label>นับจาก<select value={overviewBasis} onChange={e=>setOverviewBasis(e.target.value)}><option value="issued">วันที่เบิกจริง</option><option value="created">วันที่สร้างคำขอ</option></select></label>
        <details><summary>วิธีนับคำขอ</summary><p className="inv-muted">{from} – {to} (Bangkok). แต่ละคำขอนับครั้งเดียวในช่วงวัน รวมการเบิกบางส่วน สถานะเป็นสถานะปัจจุบัน ไม่ใช่วันผลิตเสร็จ ไม่สมมติวันเบิกของประวัติเดิมที่ไม่มีหลักฐาน</p></details>
        <ReportTable rows={categories} columns={[['category','หมวด'],['requests','คำขอในช่วงวัน'],['completed','เบิกครบ'],['partially_picked','เบิกบางส่วน'],['pending','รอหยิบ'],['cancelled','ยกเลิก'],['production_not_completed','ผลิตไม่สำเร็จ'],['legacy_completed_shipped','Legacy completed/shipped']]}/>
        {exportButton('categories',categories,[['category','หมวด'],['requests','คำขอในช่วงวัน'],['completed','เบิกครบ'],['partially_picked','เบิกบางส่วน'],['pending','รอหยิบ'],['cancelled','ยกเลิก'],['production_not_completed','ผลิตไม่สำเร็จ'],['legacy_completed_shipped','Legacy completed/shipped']], 'ส่งออกจำนวนตามหมวด')}
        <details><summary>จำนวนคำขอตามรุ่น</summary><p className="inv-muted">ตามวันสร้างคำขอ</p><ReportTable rows={summary} columns={[["legacy_completed_shipped","Completed/shipped (legacy)"],["model_name","รุ่น"],["category","หมวด"],["requests","คำขอ"],["completed","เบิกครบ"],["pending","รอหยิบ"],["partially_picked","บางส่วน"],["cancelled","ยกเลิก"],["production_not_completed","ผลิตไม่สำเร็จ"]]}/>
        {exportButton('models',summary,[['legacy_completed_shipped','Completed/shipped (legacy)'],['model_id','รหัสรุ่น'],['model_name','ชื่อรุ่นย้อนหลัง'],['category','หมวด'],['requests','คำขอ'],['completed','เบิกครบ'],['cancelled','ยกเลิก'],['production_not_completed','ผลิตไม่สำเร็จ']], 'ส่งออกสรุปรุ่น')}</details></>}
        <h3>การใช้วัตถุดิบจริงในงวด</h3><ReportTable rows={balances} columns={balanceColumns.filter(([key])=>['name','unit','issue','returned','net_usage','closing'].includes(key))}/><button onClick={()=>setTab('stock')}>ดูยอดและรายละเอียดทั้งหมด</button></>}
      {tab==='requests'&&role==='admin'&&<><p>หนึ่งแถวต่อคำขอ ไม่แปลงคู่/ข้าง และไม่ใช้ BOM ปัจจุบันคำนวณย้อนหลัง</p>{exportButton('requests',rows,requestColumns,'ส่งออกคำขอทั้งหมดในตัวกรอง')}{exportButton('requirements',requirements,[...requestColumns,['line_id','รหัสบรรทัด'],['material_id','รหัสวัตถุดิบ'],['material_name','วัตถุดิบ'],['unit','หน่วย'],['required_qty','ความต้องการตาม snapshot']], 'ส่งออกความต้องการวัตถุดิบ')}
        <ReportTable rows={rows} columns={requestColumns.filter(([key])=>!['request_id','model_id'].includes(key))}/>
        <h3>เปิดดูคำขอและวัตถุดิบย้อนหลัง</h3>{rows.slice(0,25).map(r=><details key={r.request_id}><summary>{r.order_ref} · {r.model_name} · {r.status_label}</summary>{r.accounting_evidence==='unverified'&&<p>Historical stock deduction is unverified. Snapshot quantities are requirements, not verified issues.</p>}<p>คำขอ {r.request_id}</p><ReportTable rows={requirements.filter(q=>q.request_id===r.request_id)} columns={[["material_name","วัตถุดิบ"],["required_qty","ต้องการ"],["unit","หน่วย"]]}/><p>การเบิก/คืนทุกช่วงเวลาของคำขอนี้</p><ReportTable rows={allocationRows(data.movements,data.requests,'1970-01-01','9999-12-31').filter(a=>a.request_id===r.request_id)} columns={[["occurred_at","เวลา"],["material_name","วัตถุดิบ"],["allocated_delta","เบิก (-) / คืน (+)"],["unit","หน่วย"]]}/></details>)}{rows.length>25&&<p>ค้นหาเพื่อเปิดรายละเอียดคำขอเพิ่มเติม หรือส่งออกข้อมูลครบทุกแถว</p>}</>}
      {['stock','movements'].includes(tab)&&<label>วัตถุดิบ<select value={material} onChange={e=>setMaterial(e.target.value)}><option value="">ทั้งหมด</option>{data.balances.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>}
      {tab==='stock'&&<>{exportButton('stock_balance',balances,balanceColumns,'ส่งออกยอดคงเหลือ')}<ReportTable rows={balances} columns={balanceColumns}/><p>ยอดปลายงวดอาจต่างจากยอดปัจจุบัน หากมีรายการหลังวันสิ้นสุด ยอดที่ไม่ครอบคลุมจะไม่แทนด้วยศูนย์</p><button onClick={()=>setTab('movements')}>ตรวจรายการที่ประกอบเป็นยอด</button></>}
      {tab==='movements'&&<>{exportButton('movements',moves,movementColumns,'ส่งออกประวัติทั้งหมด')}{exportButton('allocations',allocations,[['movement_id','รหัสรายการ'],['request_id','รหัสคำขอ'],['line_id','รหัสบรรทัด'],['order_ref','ออเดอร์'],['model_id','รหัสรุ่น'],['model_name','รุ่นย้อนหลัง'],['category','หมวด'],['material_name','วัตถุดิบ'],['allocated_delta','จำนวนที่จัดสรร'],['unit','หน่วย'],['occurred_at','เวลา'],['actor_id','รหัสผู้ทำรายการ']], 'ส่งออกการเบิก/คืนต่อคำขอ')}
        <ReportTable rows={moves} columns={movementColumns.filter(([key])=>['occurred_at','material_name','reason_label','delta','unit','reference'].includes(key))}/><details><summary>เอกสารและหลักฐานทั้งหมด</summary><ReportTable rows={moves} columns={projection.scoped?movementColumns.filter(([key])=>!['qty_before','qty_after','version_before','version_after'].includes(key)):movementColumns}/></details><details><summary>การจัดสรรเข้าคำขอ</summary><ReportTable rows={allocations} columns={[["category","หมวด"],["model_name","รุ่น"],["order_ref","ออเดอร์"],["material_name","วัตถุดิบ"],["allocated_delta","จำนวน"],["unit","หน่วย"],["request_id","รหัสคำขอ"]]}/></details>
        <p className="inv-muted">รายการที่ไม่มีออเดอร์ เช่น รับเข้า/นับสต็อก ยังคงแสดงครบ การนับเท่าเดิมไม่มี movement; ประวัติใบตรวจนับและเหตุผลยกเลิกฉบับเต็มต้องเพิ่มสิทธิ์อ่านผ่าน API ก่อน แสดงรหัสผู้ทำรายการเมื่อไม่มีชื่อที่อนุญาตให้อ่าน</p></>}
    </>}
  </section>;
}
